### ISSUE TITLE
Error: Cannot read property 'context' of undefined

### ISSUE THREAD

**Issue by jennie** [static-dev/spike-page-id#4]
Hi @jescalan – trying to use spike-page-id and running into this error. Combed through other examples, but this looks like it might be a bug. Edited to add: Same error with node v.6.1.0 and v6.9.0.

From the log:
```
Error: TypeError: Cannot read property 'context' of undefined
    at Spike.compileCallback (/Users/jennie/.nvm/versions/node/v7.0.0/lib/node_modules/spike/node_modules/spike-core/lib/index.js:168:31)
    at Watching._done (/Users/jennie/.nvm/versions/node/v7.0.0/lib/node_modules/spike/node_modules/webpack/lib/Compiler.js:81:7)
    at Watching.<anonymous> (/Users/jennie/.nvm/versions/node/v7.0.0/lib/node_modules/spike/node_modules/webpack/lib/Compiler.js:55:25)
    at Compiler.<anonymous> (/Users/jennie/.nvm/versions/node/v7.0.0/lib/node_modules/spike/node_modules/webpack/lib/Compiler.js:227:18)
    at Compiler.next (/Users/jennie/.nvm/versions/node/v7.0.0/lib/node_modules/spike/node_modules/tapable/lib/Tapable.js:64:18)
    at tryCatchReject (/Users/jennie/Sites/carrollandco/node_modules/spike-contentful/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/Users/jennie/Sites/carrollandco/node_modules/spike-contentful/node_modules/when/lib/makePromise.js:804:4)
    at Rejected.when (/Users/jennie/Sites/carrollandco/node_modules/spike-contentful/node_modules/when/lib/makePromise.js:625:4)
    at Pending.run (/Users/jennie/Sites/carrollandco/node_modules/spike-contentful/node_modules/when/lib/makePromise.js:483:13)
    at Scheduler._drain (/Users/jennie/Sites/carrollandco/node_modules/spike-contentful/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/Users/jennie/Sites/carrollandco/node_modules/spike-contentful/node_modules/when/lib/Scheduler.js:27:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

My reshape options look like:
``` 
reshape: (ctx) => {
    return htmlStandards({
      webpack: ctx,
      locals: { pageId: pageId(ctx), locals }
    })
  }
```

**Comment by jescalan** [comment]
Hi @jennie! Sorry about this, it's definitely a bug. I have a fix ready for it actually, let me get this shipped out 🚀

**Comment by jescalan** [comment]
Hey are you using any other plugins? Like `spike-records` or `spike-collections`?

**Comment by jennie** [comment]
@jescalan No prob! And yep, i'm using `spike-records` and `spike-contentful`.

**Comment by jescalan** [comment]
Ok, so the error actually comes from using a `template` option in one of those plugins. I have it fixed in `spike-records`, will be rolling out fixes to other plugins soon. If you want to fix immediately, take the spike page id out from the template you are using for single views in records/contentful for now 😁

**Comment by michaelcd** [comment]
We also have this issue with `spike-rooftop`.

**Comment by jescalan** [comment]
Will try to get this ironed out this week! It has been fixed in spike-records, just need to also fix it in the other repos.

**Comment by jescalan** [comment]
Ok this is fixed everywhere except for rooftop, which is in progress
